scripts:
      - name: Setup Android SDK
        script: |
          chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          yes | bash $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          bash $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"